
                      🩷 Sponsors

                  < with love & joy /> 💎

  _____________________________________________________


github: [FabianaCampanari, Quantum-Software-Development]
github: ['https://github.com/FabianaCampanari', 'https://github.com/Quantum-Software-Development']
